services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1506:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U dbuser -d aos" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 500ms
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dbuser
      POSTGRES_DB: aos
    volumes:
      - ./gis.sh:/docker-entrypoint-initdb.d/gis.sh
